2019-08-29 16:53:39,675 - metegol - ERROR - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 8, in add_player
    if mongo.find_one(config.get("PLAYERS_COLLECTION"), {"id": user_data['id']}):
TypeError: 'NoneType' object is not subscriptable
2019-08-29 16:54:35,068 - metegol - ERROR - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 8, in add_player
    if mongo.find_one(config.get("PLAYERS_COLLECTION"), {"id": user_data['id']}):
TypeError: 'NoneType' object is not subscriptable
2019-08-29 16:55:21,768 - metegol - ERROR - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 7, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 8, in add_player
    user = mongo.find_one(config.get("PLAYERS_COLLECTION"), {"id": user_data['id']})
TypeError: 'NoneType' object is not subscriptable
2019-08-29 16:57:27,946 - metegol - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 7, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 9, in add_player
    print(user_data.id)
AttributeError: 'NoneType' object has no attribute 'id'
2019-08-29 16:58:03,537 - metegol - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 7, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 9, in add_player
    print(user_data.id)
AttributeError: 'NoneType' object has no attribute 'id'
2019-08-29 16:58:15,745 - metegol - ERROR - 'Message' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 7, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 9, in add_player
    print(user_data.id)
AttributeError: 'Message' object has no attribute 'id'
2019-08-29 16:59:57,410 - metegol - ERROR - document must be an instance of dict, bson.son.SON, bson.raw_bson.RawBSONDocument, or a type that inherits from collections.MutableMapping
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 7, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 16, in add_player
    mongo.insert_one(config.get("PLAYERS_COLLECTION"), user_data)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/mongoConnection.py", line 30, in insert_one
    response = db[collection].insert_one(data)
  File "/usr/local/lib/python3.7/site-packages/pymongo/collection.py", line 689, in insert_one
    common.validate_is_document_type("document", document)
  File "/usr/local/lib/python3.7/site-packages/pymongo/common.py", line 483, in validate_is_document_type
    "collections.MutableMapping" % (option,))
TypeError: document must be an instance of dict, bson.son.SON, bson.raw_bson.RawBSONDocument, or a type that inherits from collections.MutableMapping
2019-08-29 17:00:26,205 - metegol - ERROR - 0
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 7, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 8, in add_player
    print(dict(user_data))
  File "/usr/local/lib/python3.7/site-packages/telegram/base.py", line 39, in __getitem__
    return self.__dict__[item]
KeyError: 0
2019-08-29 17:03:32,577 - metegol - ERROR - 0
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 7, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 8, in add_player
    "id": update.message.from_user.id,
  File "/usr/local/lib/python3.7/site-packages/telegram/base.py", line 39, in __getitem__
    return self.__dict__[item]
KeyError: 0
2019-08-29 17:03:32,577 - metegol - ERROR - 0
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 7, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 8, in add_player
    "id": update.message.from_user.id,
  File "/usr/local/lib/python3.7/site-packages/telegram/base.py", line 39, in __getitem__
    return self.__dict__[item]
KeyError: 0
2019-08-29 17:10:04,833 - metegol - ERROR - cannot set options after executing query
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 7, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 23, in players_list
    response = response + "\n" + users["username"]
  File "/usr/local/lib/python3.7/site-packages/pymongo/cursor.py", line 579, in __getitem__
    self.__check_okay_to_chain()
  File "/usr/local/lib/python3.7/site-packages/pymongo/cursor.py", line 390, in __check_okay_to_chain
    raise InvalidOperation("cannot set options after executing query")
pymongo.errors.InvalidOperation: cannot set options after executing query
2019-08-29 17:15:10,737 - metegol - ERROR - 'player'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 7, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 30, in player_statics
    keyboard = [ [InlineKeyboardButton(user["username"], callback_data=user["player"]) for user in users] ]
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 30, in <listcomp>
    keyboard = [ [InlineKeyboardButton(user["username"], callback_data=user["player"]) for user in users] ]
KeyError: 'player'
2019-08-29 17:16:20,982 - metegol - ERROR - 'idas'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 7, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 30, in player_statics
    keyboard = [ [InlineKeyboardButton(user["username"], callback_data=user["idas"]) for user in users] ]
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 30, in <listcomp>
    keyboard = [ [InlineKeyboardButton(user["username"], callback_data=user["idas"]) for user in users] ]
KeyError: 'idas'
2019-08-29 17:16:20,983 - metegol - ERROR - (<telegram.bot.Bot object at 0x10f891128>, <telegram.update.Update object at 0x10fcea0f0>)
2019-08-29 17:17:34,332 - metegol - ERROR - 'idas'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 8, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 30, in player_statics
    keyboard = [ [InlineKeyboardButton(user["username"], callback_data=user["idas"]) for user in users] ]
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 30, in <listcomp>
    keyboard = [ [InlineKeyboardButton(user["username"], callback_data=user["idas"]) for user in users] ]
KeyError: 'idas'
2019-08-29 17:17:34,333 - metegol - ERROR - {'id': 758840577, 'username': 'statsMetegolDevelopmentBot', 'first_name': 'statsMetegolDevelopmentBot'}
2019-08-29 17:19:19,741 - metegol - ERROR - 'idas'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 30, in player_statics
    keyboard = [ [InlineKeyboardButton(user["username"], callback_data=user["idas"]) for user in users] ]
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 30, in <listcomp>
    keyboard = [ [InlineKeyboardButton(user["username"], callback_data=user["idas"]) for user in users] ]
KeyError: 'idas'
2019-08-29 17:19:19,742 - metegol - ERROR - {'id': 758840577, 'username': 'statsMetegolDevelopmentBot', 'first_name': 'statsMetegolDevelopmentBot'}
2019-08-29 17:26:07,725 - metegol - ERROR - Can't parse inline keyboard button: field "callback_data" must be of type string
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 36, in player_statics
    update.message.reply_text('Please choose:', reply_markup=reply_markup)
  File "/usr/local/lib/python3.7/site-packages/telegram/message.py", line 455, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse inline keyboard button: field "callback_data" must be of type string
2019-08-29 17:26:07,733 - metegol - ERROR - {'id': 758840577, 'username': 'statsMetegolDevelopmentBot', 'first_name': 'statsMetegolDevelopmentBot'}
2019-08-29 17:27:18,440 - metegol - ERROR - Can't parse inline keyboard button: field "callback_data" must be of type string
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 36, in player_statics
    update.message.reply_text('Please choose:', reply_markup=reply_markup)
  File "/usr/local/lib/python3.7/site-packages/telegram/message.py", line 455, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse inline keyboard button: field "callback_data" must be of type string
2019-08-29 17:27:18,442 - metegol - ERROR - {'id': 758840577, 'username': 'statsMetegolDevelopmentBot', 'first_name': 'statsMetegolDevelopmentBot'}
2019-08-29 17:31:02,952 - metegol - ERROR - can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 31, in player_statics
    [ InlineKeyboardButton(user["username"], callback_data= "player&"+user["id"]) for user in users]
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 31, in <listcomp>
    [ InlineKeyboardButton(user["username"], callback_data= "player&"+user["id"]) for user in users]
TypeError: can only concatenate str (not "int") to str
2019-08-29 17:31:18,675 - metegol - ERROR - can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 31, in player_statics
    [ InlineKeyboardButton(user["username"], callback_data= "player&"+str(user["id"])) for user in users]
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 31, in <listcomp>
    [ InlineKeyboardButton(user["username"], callback_data= "player&"+str(user["id"])) for user in users]
TypeError: can only concatenate str (not "int") to str
2019-08-29 17:31:18,675 - metegol - ERROR - can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 31, in player_statics
    [ InlineKeyboardButton(user["username"], callback_data= "player&"+str(user["id"])) for user in users]
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 31, in <listcomp>
    [ InlineKeyboardButton(user["username"], callback_data= "player&"+str(user["id"])) for user in users]
TypeError: can only concatenate str (not "int") to str
2019-08-29 17:50:13,859 - metegol - ERROR - 'NoneType' object has no attribute 'chat_id'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 41, in _get_player_statics
    bot.send_message(chat_id=update.message.chat_id, text="Probanding" )
AttributeError: 'NoneType' object has no attribute 'chat_id'
2019-08-29 17:50:13,859 - metegol - ERROR - 'NoneType' object has no attribute 'chat_id'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 41, in _get_player_statics
    bot.send_message(chat_id=update.message.chat_id, text="Probanding" )
AttributeError: 'NoneType' object has no attribute 'chat_id'
2019-08-29 17:50:13,859 - metegol - ERROR - 'NoneType' object has no attribute 'chat_id'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 41, in _get_player_statics
    bot.send_message(chat_id=update.message.chat_id, text="Probanding" )
AttributeError: 'NoneType' object has no attribute 'chat_id'
2019-08-29 17:50:13,863 - metegol - ERROR - 'NoneType' object has no attribute 'chat_id'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 41, in _get_player_statics
    bot.send_message(chat_id=update.message.chat_id, text="Probanding" )
AttributeError: 'NoneType' object has no attribute 'chat_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/callbacks.py", line 11, in inline_button_callback
    _get_player_statics(bot, update, data[1:])
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 13, in func_wrapper
    bot.send_message(chat_id=update.message.chat_id, text="Exception: " + str(ex))
AttributeError: 'NoneType' object has no attribute 'chat_id'
2019-08-29 17:50:13,863 - metegol - ERROR - 'NoneType' object has no attribute 'chat_id'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 41, in _get_player_statics
    bot.send_message(chat_id=update.message.chat_id, text="Probanding" )
AttributeError: 'NoneType' object has no attribute 'chat_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/callbacks.py", line 11, in inline_button_callback
    _get_player_statics(bot, update, data[1:])
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 13, in func_wrapper
    bot.send_message(chat_id=update.message.chat_id, text="Exception: " + str(ex))
AttributeError: 'NoneType' object has no attribute 'chat_id'
2019-08-29 17:50:13,863 - metegol - ERROR - 'NoneType' object has no attribute 'chat_id'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 41, in _get_player_statics
    bot.send_message(chat_id=update.message.chat_id, text="Probanding" )
AttributeError: 'NoneType' object has no attribute 'chat_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/callbacks.py", line 11, in inline_button_callback
    _get_player_statics(bot, update, data[1:])
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 13, in func_wrapper
    bot.send_message(chat_id=update.message.chat_id, text="Exception: " + str(ex))
AttributeError: 'NoneType' object has no attribute 'chat_id'
2019-08-29 17:51:13,837 - metegol - ERROR - _get_player_statics() missing 1 required positional argument: 'player'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
TypeError: _get_player_statics() missing 1 required positional argument: 'player'
2019-08-29 17:51:13,837 - metegol - ERROR - _get_player_statics() missing 1 required positional argument: 'player'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
TypeError: _get_player_statics() missing 1 required positional argument: 'player'
2019-08-29 17:51:13,837 - metegol - ERROR - _get_player_statics() missing 1 required positional argument: 'player'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
TypeError: _get_player_statics() missing 1 required positional argument: 'player'
2019-08-29 17:51:13,838 - metegol - ERROR - 'list' object has no attribute 'send_message'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
TypeError: _get_player_statics() missing 1 required positional argument: 'player'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/callbacks.py", line 11, in inline_button_callback
    _get_player_statics(data[1:], update.callback_query.message.chat_id)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 13, in func_wrapper
    bot.send_message(chat_id=update.message.chat_id, text="Exception: " + str(ex))
AttributeError: 'list' object has no attribute 'send_message'
2019-08-29 17:51:13,838 - metegol - ERROR - 'list' object has no attribute 'send_message'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
TypeError: _get_player_statics() missing 1 required positional argument: 'player'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/callbacks.py", line 11, in inline_button_callback
    _get_player_statics(data[1:], update.callback_query.message.chat_id)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 13, in func_wrapper
    bot.send_message(chat_id=update.message.chat_id, text="Exception: " + str(ex))
AttributeError: 'list' object has no attribute 'send_message'
2019-08-29 17:51:13,838 - metegol - ERROR - 'list' object has no attribute 'send_message'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
TypeError: _get_player_statics() missing 1 required positional argument: 'player'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/callbacks.py", line 11, in inline_button_callback
    _get_player_statics(data[1:], update.callback_query.message.chat_id)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 13, in func_wrapper
    bot.send_message(chat_id=update.message.chat_id, text="Exception: " + str(ex))
AttributeError: 'list' object has no attribute 'send_message'
2019-08-29 17:51:46,981 - metegol - ERROR - _get_player_statics() missing 1 required positional argument: 'chat_id'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/callbacks.py", line 11, in inline_button_callback
    _get_player_statics(data[1:], update.callback_query.message.chat_id)
TypeError: _get_player_statics() missing 1 required positional argument: 'chat_id'
2019-08-29 17:51:46,981 - metegol - ERROR - _get_player_statics() missing 1 required positional argument: 'chat_id'
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 10, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/callbacks.py", line 11, in inline_button_callback
    _get_player_statics(data[1:], update.callback_query.message.chat_id)
TypeError: _get_player_statics() missing 1 required positional argument: 'chat_id'
2019-08-29 18:02:35,947 - metegol - ERROR - name 'user_data' is not defined
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 11, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/callbacks.py", line 12, in inline_button_callback
    _remove_player(bot, data[1:], update.callback_query.message.chat_id)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 55, in _remove_player
    mongo.remove_by_query(config.get("PLAYERS_COLLECTION"), {"id": user_data['id']})
NameError: name 'user_data' is not defined
2019-08-29 18:02:35,947 - metegol - ERROR - name 'user_data' is not defined
Traceback (most recent call last):
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/utils.py", line 11, in func_wrapper
    func(*args, **kwargs)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/callbacks.py", line 12, in inline_button_callback
    _remove_player(bot, data[1:], update.callback_query.message.chat_id)
  File "/Users/juanpirossi/Documents/personal-projects/metegolBotTelegram/src/players.py", line 55, in _remove_player
    mongo.remove_by_query(config.get("PLAYERS_COLLECTION"), {"id": user_data['id']})
NameError: name 'user_data' is not defined
